### ISSUE TITLE
[BUG]: Type ... is not assignable to type 'never' when calling requestReviewers

### ISSUE THREAD

**Issue by jakebailey** [octokit/types.ts#534] opened 2023-04-28 18:11 UTC
### What happened?

With just:

```
import { Octokit } from "@octokit/rest";

const gh = new Octokit();

gh.pulls.requestReviewers({
	owner: "owner",
	repo: "repo",
	pull_number: 1234,
	reviewers: ["foo", "bar", "baz"],
})
```

All properties of the options are flagged as errors.

You can see this at the moment in the TS playground (which does download the types): [Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeQMYwga2PAvnAMyghDgCIABCdLHAeigFMBnGMgbgChPUIA7VnADmACzgBeOH0YB3FDWwwAFAEounUQDowAVwA2e5pqYBHHSxgAlRgDdgsxlGZKEnAJAQZ0qAC5yn7zIAGncmSD8yMIhg910DAH0+HRAAI0c-AEYAJgBmABYQtyY7Byc-AG0yAghooPIUgEMoYPqGgC8yAF0Q3BUgA)

### Versions

@octokit/types@9.1.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jakebailey** [comment] 2023-04-28 18:15
Per https://github.com/octokit/types.ts/issues/528#issuecomment-1527921562 I may have been too quick at the draw, but, the just released v9.2.0 also has this problem.

**Comment by wolfy1339** [comment] 2023-04-28 18:33
This is a different problem than #528...

This is caused by GitHub itself. The OpenAPI spec isn't quite correct for many endpoints

Example endpoint:
`PATCH /gists/{gist_id}`
```ts
"gists/update": {
   [ ... ]
    requestBody: {
      content: {
        "application/json":
          | ({
              [ ... ]
              files?: {
                [key: string]:
                  | (
                      | ({
                          /** @description The new content of the file. */
                          content?: string;
                          /** @description The new filename for the file. */
                          filename?: string | null;
                        } & (
                          | Record<string, never>
                          | Record<string, never>
                          | Record<string, never>
                        ))
                      | null
                    )
                  | undefined;
              };
            } & (Record<string, never> | Record<string, never>))
          | null;
      };
    };
  };
```
```json
"/gists/{gist_id}": {
[ ... ]
"patch": {
        "summary": "Update a gist",
        "description": "Allows you to update a gist's description and to update, delete, or rename gist files. Files from the previous version of the gist that aren't explicitly changed during an edit are unchanged.",
        "tags": [
          "gists"
        ],
        "operationId": "gists/update",
        "externalDocs": {
          "description": "API method documentation",
          "url": "https://docs.github.com/rest/reference/gists/#update-a-gist"
        },
        "parameters": [
          {
            "$ref": "#/components/parameters/gist-id"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                   [ ... ]
                  "files": {
                    [ ... ]
                    "type": "object",
                    "additionalProperties": {
                      "type": "object",
                      "nullable": true,
                      "properties": {
                        "content": {
                          "description": "The new content of the file.",
                          "type": "string"
                        },
                        "filename": {
                          "description": "The new filename for the file.",
                          "type": "string",
                          "nullable": true
                        }
                      },
                      "anyOf": [
                        {
                          "required": [
                            "content"
                          ]
                        },
                        {
                          "required": [
                            "filename"
                          ]
                        },
                        {
                          "type": "object",
                          "maxProperties": 0
                        }
                      ]
                    }
                  }
                },
                "anyOf": [
                  {
                    "required": [
                      "description"
                    ]
                  },
                  {
                    "required": [
                      "files"
                    ]
                  }
                ],
                "type": "object",
                "nullable": true
              },
            [ ... ]
              }
            }
          }
        },
  [ ... ]
      },

**Comment by wolfy1339** [comment] 2023-04-28 18:40
I've narrowed it down to the following circumstance:

The spec is trying to specify that either `reviewers` or `team_reviewers` is present at a time, by trying to use `anyOf` and `required`.
That isn't how the JSON schema spec that OpenAPI is built on works. It will always result in undefined behaviour

Before `openapi-typescript` handled these quirks, but doesn't anymore.

**Comment by wolfy1339** [comment] 2023-04-28 18:41
/cc @timrogers @nickfloyd 
Can you point out this bug to the relevant team so it can get fixed

**Comment by kfcampbell** [comment] 2023-05-05 17:56
I've brought it up in Slack, though I can't speculate at a time frame for resolution.

**Comment by kfcampbell** [comment] 2023-05-05 18:42
@wolfy1339 now that your override has been merged, we should get automated dependency updates with the next lock file maintenance PRs, right?

**Comment by wolfy1339** [comment] 2023-05-05 18:43
Sometimes, that may be the case.

Most of the time updates to this package is handled by octokitbot

**Comment by wolfy1339** [comment] 2023-05-12 02:13
I'm closing out this issue as everything seems to be in working order now.

Please file a new issue if a problem arises

**Closed by wolfy1339** 2023-05-12 02:13 UTC
Labels: Type: Bug, Status: Blocked
