### ISSUE TITLE
Endpoints['PATCH /repos/{owner}/{repo}/check-runs/{check_run_id}']['parameters'] gives broken types in version newer than v6.3.2

### ISSUE THREAD

**Issue by tlbdk** [octokit/types.ts#283] opened 2021-03-08 10:16 UTC
**How to recreate the issue**

Exactly same issues as: https://github.com/octokit/types.ts/issues/274

Create a test project:

``` bash
npm init -y && npm install typescript @octokit/types
```

Generates this package.json file:

``` json
{
  "name": "test-repo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@octokit/types": "^6.11.0",
    "typescript": "^4.2.2"
  }
}
```
Create test.ts:

``` typescript 
import { Endpoints } from '@octokit/types'

type listUserReposParameters = Endpoints['PATCH /repos/{owner}/{repo}/check-runs/{check_run_id}']['parameters']

const test: listUserReposParameters = {
    name: '',
    head_sha: '',
    owner: '',
    repo: '',
    status: 'completed'
}
```

``` bash
./node_modules/.bin/tsc test.ts
```

Gives the following error and the type that it constructed seems very broken:

``` text
test.ts:10:5 - error TS2322: Type 'string' is not assignable to type 'never'.

10     status: 'completed'
       ~~~~~~

  node_modules/@octokit/openapi-types/dist-types/generated/types.d.ts:19876:21
    19876                     status?: "completed";
                              ~~~~~~
    The expected type comes from property 'status' which is declared here on type '{ owner: string; repo: string; check_run_id: number; } & Partial<{ status?: "completed"; } & { [key: string]: any; }> & Partial<{ status?: "queued" | "in_progress"; } & { [key: string]: any; }> & { ...; }'


Found 1 error.
```

Trying with v6.3.2 works:

``` bash
npm install @octokit/types@6.3.2
````

``` bash
tsc test.ts
```

Diff is here:
https://github.com/octokit/types.ts/compare/v6.3.2...v6.4.0

**Comment by gr2m** [comment] 2021-03-08 18:55
hmm sorry for that, I thought we had the problem with the `status` parameter resolved. By the way you could have reopened #274 in this case, but either works

**Comment by gr2m** [comment] 2021-03-08 19:18
> By the way you could have reopened #274 in this case, but either works

ah sorry I see now it's a different path, I got it

**Comment by gr2m** [comment] 2021-03-09 23:34
reported the problem here: https://github.com/github/rest-api-description/issues/228. Once resolved in https://github.com/github/rest-api-description, `@octokit/types` will get updated shortly after by our bots

**Comment by gr2m** [comment] 2021-04-22 19:11
The original problem was resolved at github/rest-api-description#228, but now `status` type is set to `undefined`. It's now likely a problem in how we transpile the OpenAPI spec to TypeScript, I'll have a look

**Comment by wolfy1339** [comment] 2023-09-22 18:50
@tlbdk @jamacku Can you reproduce this issue with the latest version?

**Comment by jamacku** [comment] 2023-09-25 07:28
@wolfy1339 The `status` type is fixed, but the `conclusion` is still emitting the same error message.

```ts
Type 'unknown' is not assignable to type '"action_required" | "cancelled" | "failure" | "neutral" | "success" | "skipped" | "stale" | "timed_out" | undefined'.
```

**Comment by jamacku** [comment] 2023-10-24 08:01
@wolfy1339, I can't reproduce this issue with the latest version: `"@octokit/types": "^12.0.0"`. It's fixed for me. Thank you.

**Closed** 2023-10-24 10:09 UTC
Labels: Type: Bug, typescript, Status: Blocked
